---
sidebar: sidebar 
permalink: concept-cvs-aws.html 
keywords: cloud volumes service for aws, cloud volumes, cloud volumes service subscription, access key, secret key 
summary: NetApp Cloud Volumes Service for AWS 是雲端原生檔案服務、可透過 NFS 和 SMB 提供 NAS 磁碟區的 All Flash 效能。此服務可讓任何工作負載（包括舊版應用程式）在 AWS 雲端上執行。 
---
= 深入瞭 Cloud Volumes Service 解適用於 AWS 的功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Cloud Volumes Service for AWS 是雲端原生檔案服務、可透過 NFS 和 SMB 提供 NAS 磁碟區的 All Flash 效能。此服務可讓任何工作負載（包括舊版應用程式）在 AWS 雲端上執行。


NOTE: 隨之推出 link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html["Amazon FSX for ONTAP Sf"^]、Cloud Volumes Service 您無法再在Cloud Manager中建立AWS工作環境的新功能。不過、如果您先前已將Cloud Volumes Service 適用於AWS工作環境的功能強化至Cloud Manager、則可以繼續建立及管理磁碟區。



== 使用適用於 AWS 的 Cloud Volumes Service 效益

AWS 的支援提供下列優點： Cloud Volumes Service

* 完全託管的服務、因此不需要設定或管理儲存設備
* 支援 NFSv3 和 NFSv4.1 、以及 SMB 3.0 和 3.1.1 NAS 傳輸協定
* 安全存取 Linux 和 Windows Elastic Container Service （ ECS ）執行個體、並支援下列項目：
+
** Amazon Linux 2 、 Red Hat Enterprise Linux 7.5 、 SLES 12 SP3 及 Ubuntu 16.04 LTS
** Windows Server 2008 R2 、 Windows Server 2012 R2 和 Windows Server 2016


* 可選擇搭售和隨用隨付定價




== 成本

由 AWS 開發的磁碟區 Cloud Volumes Service 會根據您訂閱的服務而收費、而非透過 Cloud Manager 。

從 Cloud Volumes Service Cloud Manager 探索 AWS 區域或磁碟區不需付費。



== 快速入門

請依照下列步驟快速入門、或前往下一節以取得完整詳細資料。

[role="quick-margin-para"]
您必須設定AWS Cloud Volumes Service 以供其使用、並訂閱其中一項 https://aws.amazon.com/marketplace/search/results?x=0&y=0&searchTerms=netapp+cloud+volumes+service["AWS Marketplace 上的 NetApp Cloud Volumes Service 產品"^] 並在Cloud Manager中設定現有的CVS for AWS工作環境、以建立及管理磁碟區。

[role="quick-margin-para"]
使用現有的CVS for AWS工作環境、您可以使用Cloud Manager為現有的CVS for AWS訂閱建立、掛載及管理雲端磁碟區。



== 取得協助

使用 Cloud Manager 聊天室來回答一般服務問題。

如需雲端磁碟區的相關技術支援問題、請使用 Cloud Volumes Service 位在支援選項卡上的 20 位數「 930 」序號（英文）。開啟網路票證或致電尋求支援時、請使用此支援 ID 。請務必啟動 Cloud Volumes Service 您的不支援序號 Cloud Volumes Service 、以便從支援中心使用者介面獲得支援。 https://docs.netapp.com/us-en/cloud_volumes/aws/task_activating_support_entitlement.html["以下將說明這些步驟"^]。



== 限制

* Cloud Manager 不支援 Cloud Volumes Service 使用支援在工作環境之間進行資料複寫的功能。
* 不支援從 Cloud Volumes Service Cloud Manager 移除您的 AWS 訂購功能。您只能透過 Cloud Volumes Service 適用於 AWS 介面執行此動作。




== 相關連結

* https://cloud.netapp.com/cloud-volumes-service-for-aws["NetApp Cloud Central ： Cloud Volumes Service AWS 適用的解決方案"^]
* https://docs.netapp.com/us-en/cloud_volumes/aws/["NetApp Cloud Volumes Service for AWS 文件"^]

